version: '3.8'

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    volumes:
      - /home:/home  # Mount home directory to monitor
    ports:
      - "8000:8000"
      - "9090:9090"  # Prometheus metrics
    depends_on:
      - alert-handler
      - backup-node
    networks:
      - monitoring

  alert-handler:
    build:
      context: .
      dockerfile: Dockerfile.alert_handler
    ports:
      - "8000:8000"
      - "9001:9001"  # Prometheus metrics
    environment:
      - ADMIN_API_URL=http://admin-system/receive-alert
    networks:
      - monitoring

  backup-node:
    build:
      context: .
      dockerfile: Dockerfile.backup_node
    volumes:
      - ./backups:/app/backups  # Persistent backup storage
    ports:
      - "9000:9000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
    driver: local