version: "3.8"

services:
  client-agent:
    build:
      context: ./clientAgent
      dockerfile: Dockerfile
    volumes:
      - /home/:/home/
    environment:
      - SERVER_URL=http://alert-handler:8000/alert
    depends_on:
      - alert-handler

  alert-handler:
    build:
      context: ./alertHandler
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9001:9001"
    environment:
      - ADMIN_API_URL=http://admin-system/receive-alert

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus