apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "client-agent"
        static_configs:
          - targets: ["client-agent:9000"]
      - job_name: "alert-handler"
        static_configs:
          - targets: ["alert-handler:9001"]
