apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'agent'
        static_configs:
          - targets: ['agent:9000']

      - job_name: 'alert-handler'
        static_configs:
          - targets: ['alert-handler:9001']

      - job_name: 'backup-node'
        static_configs:
          - targets: ['backup-node:9002']

