apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: admin-system
  name: admin-system
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-system
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: admin-system
    spec:
      containers:
        - env:
            - name: PROMETHEUS_PORT
              value: "9002"
          image: retudocker/admin-system-image:latest
          name: admin-system
          ports:
            - containerPort: 8001
              protocol: TCP
            - containerPort: 9002
              protocol: TCP
      restartPolicy: Always
