apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: admin-system
  name: admin-system
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: "9002"
      port: 9002
      targetPort: 9002
  selector:
    io.kompose.service: admin-system
