apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: alert-handler
  name: alert-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alert-handler
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: alert-handler
    spec:
      containers:
        - env:
            - name: ADMIN_API_URL
              value: http://admin-system/receive-alert
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_API_KEY
                  name: env
            - name: PROMETHEUS_PORT
              value: "9001"
            - name: VIRUSTOTAL_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: VIRUSTOTAL_API_KEY
                  name: env
          image: retudocker/alert-handler-image:latest
          name: alert-handler
          ports:
            - containerPort: 8002
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
      restartPolicy: Always
