apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backup-node
  name: backup-node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backup-node
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: backup-node
    spec:
      containers:
        - image: retudocker/backup-node-image:latest
          name: backup-node
          ports:
            - containerPort: 8003
              protocol: TCP
          volumeMounts:
            - mountPath: /app/backups
              name: backup-node-claim0
      restartPolicy: Always
      volumes:
        - name: backup-node-claim0
          persistentVolumeClaim:
            claimName: backup-node-claim0
