apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-handler
  template:
    metadata:
      labels:
        app: alert-handler
    spec:
      containers:
      - name: alert-handler
        image: myrepo/alert-handler:latest
        env:
        - name: ADMIN_API_URL
          value: "http://admin-system/receive-alert"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: alert-handler
spec:
  selector:
    app: alert-handler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP