apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-handler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alert-handler
  template:
    metadata:
      labels:
        app: alert-handler
    spec:
      containers:
        - name: alert-handler
          image: alert-handler:latest
          ports:
            - containerPort: 8000
            - containerPort: 9001
          env:
            - name: ADMIN_API_URL
              value: "http://admin-system/receive-alert"
---
apiVersion: v1
kind: Service
metadata:
  name: alert-handler
spec:
  selector:
    app: alert-handler
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 9001
      targetPort: 9001
