apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out=k8s-manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backup-node
  name: backup-node
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: backup-node
